steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudrun-github-dev/github.com/davidjohanneslars/cloudrun-project:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudrun-github-dev/github.com/davidjohanneslars/cloudrun-project:$COMMIT_SHA']  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloudrun-github-dev', '--region=europe-north1', '--platform=managed', '--image=gcr.io/cloudrun-github-dev/github.com/davidjohanneslars/cloudrun-project:$COMMIT_SHA']    


