steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudrun-github-dev/github.com/davidjohanneslars/cloudrun-project:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/cloudrun-github-dev/github.com/davidjohanneslars/cloudrun-project:$COMMIT_SHA']  
